# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:42
from __future__ import unicode_literals

from django.db import migrations
import django_rdkit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='bfp',
            field=django_rdkit.models.fields.BfpField(blank=True, null=True),
        ),
    ]
