# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0003_chembl_chembl_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl',
            name='compound',
        ),
        migrations.AddField(
            model_name='chembl',
            name='compound',
            field=models.ManyToManyField(blank=True, null=True, to='compounds.Compound'),
        ),
        migrations.AlterField(
            model_name='chembl_info',
            name='chembl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBL'),
        ),
    ]
