# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0005_auto_20170930_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl',
            name='canonical_smi',
        ),
        migrations.RemoveField(
            model_name='chembl',
            name='max_phase',
        ),
        migrations.RemoveField(
            model_name='chembl',
            name='oral',
        ),
        migrations.RemoveField(
            model_name='chembl',
            name='pref_name',
        ),
        migrations.RemoveField(
            model_name='chembl',
            name='prodrug',
        ),
        migrations.RemoveField(
            model_name='chembl',
            name='tanimoto',
        ),
        migrations.RemoveField(
            model_name='chembl_info',
            name='assay_id',
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='activity_chembl_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='canonical_smi',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='max_phase',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='oral',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='pref_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='prodrug',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chembl_info',
            name='tanimoto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
