# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0010_chembl_chembl_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl_info',
            name='activity_chembl_id',
        ),
        migrations.RemoveField(
            model_name='chembl_info',
            name='activity_id',
        ),
    ]
