# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0011_auto_20171001_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChEMBL_Assay_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.IntegerField(blank=True, null=True)),
                ('chembl_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBL')),
            ],
        ),
    ]
