# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0012_chembl_assay_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='chembl_assay_id',
            name='chembl_id',
        ),
        migrations.RemoveField(
            model_name='chembl_info',
            name='chembl_id',
        ),
        migrations.DeleteModel(
            name='ChEMBL',
        ),
        migrations.DeleteModel(
            name='ChEMBL_Assay_id',
        ),
        migrations.DeleteModel(
            name='ChEMBL_info',
        ),
    ]
