# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0014_chembl_chembl_assay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chembl_assay_id',
            name='assay_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
