# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0016_compound_ms_diseases_drugs_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structrue_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_link', models.URLField(blank=True, null=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound')),
            ],
        ),
        migrations.RenameModel(
            old_name='Compound_MS',
            new_name='Cid_MS',
        ),
        migrations.RemoveField(
            model_name='cid_ms',
            name='compound',
        ),
        migrations.AddField(
            model_name='cid_ms',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CID'),
        ),
    ]
