# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0017_auto_20171025_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cid_ms',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='structrue_ms',
            name='structure',
        ),
        migrations.DeleteModel(
            name='Cid_MS',
        ),
        migrations.DeleteModel(
            name='Structrue_MS',
        ),
    ]
