# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0019_structrue_ms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Structrue_MS',
            new_name='Compound_MS',
        ),
    ]
