# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0020_auto_20171025_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound_ms',
            name='structure',
        ),
        migrations.DeleteModel(
            name='Compound_MS',
        ),
    ]
