# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0021_auto_20171025_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound_MS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_link', models.URLField(blank=True, null=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound')),
            ],
        ),
    ]
