# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0023_tcmid_herb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TCMID_herb',
            new_name='TCMID_herbs',
        ),
    ]
