# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0024_auto_20171025_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcmid_herbs',
            name='compounds',
        ),
        migrations.DeleteModel(
            name='TCMID_herbs',
        ),
    ]
