# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0026_tcmid_herbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcmid_herbs',
            name='compounds',
        ),
        migrations.DeleteModel(
            name='TCMID_Herbs',
        ),
    ]
