# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0032_tcmid_herbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='tcmid_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
