# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0034_target_uniprot_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='related_ingredients',
            new_name='compounds',
        ),
    ]
