# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0035_auto_20171026_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='gene_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='tcmid_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='uniprot_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='uniprot_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
