# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0036_auto_20171026_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='compounds',
        ),
        migrations.RemoveField(
            model_name='target',
            name='related_diseases',
        ),
        migrations.RemoveField(
            model_name='target',
            name='related_drugs',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
