# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0042_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='first_Chinese_catogary',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='first_English_catogary',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='second_Chinese_catogary',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='second_English_catogary',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=2012, null=True),
        ),
    ]
