# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0046_remove_compound_mol_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='mol_file',
            field=models.FileField(blank=True, null=True, upload_to='mol_files/'),
        ),
    ]
