# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0048_remove_compound_mol_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='mol_image',
            field=models.ImageField(blank=True, null=True, upload_to='mol_images/'),
        ),
    ]
