# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0050_auto_20171026_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='mol_file',
            field=models.FileField(blank=True, null=True, upload_to='mol_files/'),
        ),
        migrations.AddField(
            model_name='compound',
            name='mol_image',
            field=models.ImageField(blank=True, null=True, upload_to='mol_images/'),
        ),
    ]
