# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0051_auto_20171026_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundFirstCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chinese_first_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('English_first_catagory', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompoundSecondCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chinese_second_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('English_second_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('smiles', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='compound',
            name='first_Chinese_catogary',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='first_English_catogary',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='second_Chinese_catogary',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='second_English_catogary',
        ),
        migrations.AddField(
            model_name='compound',
            name='first_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CompoundFirstCatagory'),
        ),
        migrations.AddField(
            model_name='compound',
            name='second_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CompoundSecondCatagory'),
        ),
    ]
