# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0052_auto_20171030_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='first_catagory',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='second_catagory',
        ),
        migrations.AddField(
            model_name='compoundfirstcatagory',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound'),
        ),
        migrations.AddField(
            model_name='compoundsecondcatagory',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.Compound'),
        ),
    ]
