# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0054_auto_20171030_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compoundsecondcatagory',
            old_name='catagory_smiles',
            new_name='catagory_smile',
        ),
    ]
