# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0055_auto_20171031_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundfirstcatagory',
            name='compound',
        ),
        migrations.RemoveField(
            model_name='compoundsecondcatagory',
            name='compound',
        ),
        migrations.DeleteModel(
            name='CompoundFirstCatagory',
        ),
        migrations.DeleteModel(
            name='CompoundSecondCatagory',
        ),
    ]
