# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0060_auto_20171101_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundFirstCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chinese_first_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('English_first_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('compounds', models.ManyToManyField(blank=True, to='compounds.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundSecondCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chinese_second_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('English_second_catagory', models.CharField(blank=True, max_length=1024, null=True)),
                ('catagory_smile', models.CharField(blank=True, max_length=1024, null=True)),
                ('compounds', models.ManyToManyField(blank=True, to='compounds.Compound')),
                ('first_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CompoundFirstCatagory')),
            ],
        ),
    ]
