# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0063_compoundfirstcatagory_compoundsecondcatagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChEMBL',
            new_name='SimilarChEMBL',
        ),
    ]
