# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0066_remove_compoundsecondcatagory_first_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoundsecondcatagory',
            name='first_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.CompoundFirstCatagory'),
        ),
    ]
