# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0067_compoundsecondcatagory_first_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundsecondcatagory',
            name='first_category',
        ),
    ]
