# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0069_compoundsecondcatagory_first_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChEMBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemblid', models.CharField(blank=True, max_length=1024, null=True, verbose_name='ChEMBL ID')),
                ('url', models.URLField(blank=True, max_length=1024, verbose_name='URL link to ChEMBL database')),
                ('canonical_smi', models.CharField(blank=True, max_length=1024, null=True)),
                ('max_phase', models.SmallIntegerField(blank=True, null=True)),
                ('prodrug', models.SmallIntegerField(blank=True, null=True)),
                ('oral', models.SmallIntegerField(blank=True, null=True)),
                ('pref_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('tanimoto', models.FloatField(blank=True, null=True)),
                ('same_or_similarity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ChEMBL ID',
            },
        ),
        migrations.RemoveField(
            model_name='compound',
            name='similar_chembls',
        ),
        migrations.AlterField(
            model_name='chembl_assay_id',
            name='chembl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.ChEMBL'),
        ),
        migrations.DeleteModel(
            name='SimilarChEMBL',
        ),
    ]
