# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0071_auto_20171101_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl_assay_id',
            name='chembl_id',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='similar_chembls',
        ),
        migrations.DeleteModel(
            name='ChEMBL_Assay_id',
        ),
        migrations.DeleteModel(
            name='SimilarChEMBL',
        ),
    ]
