# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0073_auto_20171101_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='similar_chembls',
        ),
    ]
