# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0074_remove_compound_similar_chembls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='chembl_url',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='chemblid',
        ),
    ]
