# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0075_auto_20171101_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl_assay_id',
            name='chembl_id',
        ),
        migrations.DeleteModel(
            name='ChEMBL_Assay_id',
        ),
    ]
