# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0076_auto_20171101_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimilarChEMBL',
            new_name='ChEMBL',
        ),
    ]
