# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0078_chembl_assay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chembl',
            name='same_or_similar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
