# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0080_compound_chembls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chembl_assay_id',
            name='chembl_id',
        ),
    ]
