# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0081_remove_chembl_assay_id_chembl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chembl',
            name='assay_chembl_ids',
            field=models.ManyToManyField(blank=True, to='compounds.ChEMBL_Assay_id'),
        ),
    ]
