# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0083_remove_chembl_assay_chembl_ids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChEMBL_Assay_id',
            new_name='Assay_Chembl_id',
        ),
    ]
