# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0085_chembl_assay_chembl_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assay_chembl_id',
            old_name='assay_id',
            new_name='assay_chembl_id',
        ),
    ]
