# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0086_auto_20171102_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Chembl_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_chembl_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('doc_chembl_id_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target_Chembl_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_chembl_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('target_chembl_id_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assay_chembl_id',
            name='assay_chembl_id_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
