# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0087_auto_20171102_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='chembl',
            name='doc_chembl_ids',
            field=models.ManyToManyField(blank=True, to='compounds.Doc_Chembl_id'),
        ),
        migrations.AddField(
            model_name='chembl',
            name='target_chembl_ids',
            field=models.ManyToManyField(blank=True, to='compounds.Target_Chembl_id'),
        ),
    ]
