# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0096_compound_chembls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='chembls',
        ),
    ]
