# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds', '0100_compound_chembls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chembl',
            name='canonical_smi',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
